---
title: "First Knit"
author: "Brian Umandap"
output: 
  html_document:
    number_sections: true
    toc: true
    toc_depth: 5
date: "`r Sys.Date()`"   
---

# A Little Survey

Here are just a few questions so I can get to know you and so you can get practice submitting an assignment in Canvas.  For each question, insert your answer underneath. Make sure each answer is at the minimum a complete sentence with correctly spelled words and correct puncuation. 

## A short history of you.  
Where did you attend High School, and did you graduate? Compare english class to math, is one easier for you than the other? Finally which subject did you do the best in? Your answer should have at least two sentences devoted to each question.  
  
### my answer     
  
I attended Quartz Hill High School. I graduated Class of 2022. For me, english is much more easier to math. I feel like English is easier because it's just more reading and understanding concepts while math is more based on learning formulas. I did better in English. I only did better in English because I fully understood what I was learning compared to Math. 
     


## Your computer and your and its capability?  
 For this class  you need a computer you can use at home.  So, what kind is it (windows, Apple, Linux)?  On a scale of 1 to 10, where 1 is a total dummy (doesn't know a mouse from a keyboard) and 10 is a complete geek (knows computer stuff in and out) How do you rate yourself?  You also need to have have internet access. How is your connection to the internet where you live?

### my answer   
  I have a windows computer. For me on a scale of 1-10, I would be 8.5/10. Yes I do have internet connection and it is strong.
   

## Others and You?   
What name do you prefer to be called by your classmates and instructor, if your buddys call you something but you want people in the class to call you something else - what would that be? 

### my answer     
  I am fine with people calling me by my real name Brian.
   
 




## Aspirations?   
What do you want to achieve in life?  What college subject do you think would be of the greatest interest to you? What degree or certificate are you trying to achieve?

### my answer     
  
   I want to achieve a very loving, adventurous and wealthy life.The college subject that would be the greatest interest to me is Biology. The degree that I am trying to achieve is to get my PHD or my Master's degree.
 




## Past adventures?  
Have you ever gone to foreign countries, if so which ones, if not Where might you go in the future?  Have you ever been in the military, if so which branch, if not which branch would you choose if you got drafted, and why?

### my answer     
  
   I have been to the Philippines. I would like to visit Japan sometime in the future as well. The branch I would choose if I got drafted would be the Marines. I would choose the Marines because I like being in stressful environments since I feel like I thrive in them and would like to serve my country on the front line.
  




## Why are you taking Statistics?  
Did you take Math 115 or Math 116 ?  Did you know Math 115 only satisfies a general education requirement but that Math 116 counts as taking statistics in several transfer institutions??  
What grade do you need to attain in stats to not upset your future plans, What is your plan?  
 

### my answer     
  I have taken Math 115 in the summer for my general education requirement. Yes I did know that Math 115 satisfies only the general education requirement. I am taking Math 116 so I can transfer to the universities I would to go to, mainly UCI. The grade that I need to attain in stats is an A+. My plan is to get good grades in every class I take so I can have an easier time to transfer to UCI and get accepted. 
   
 






  




